KS-4-2-operators create
BerStep/KotlinSprint pull request #21
Opened 2024-09-25 10:54 UTC by BerStep

2024-09-25 19:00 UTC, ievetrovdev requested changes

2024-09-25 19:00 UTC, ievetrovdev commented on src/main/kotlin/lesson4/lesson4_task2.kt
> +const val MAX_VOLUME = 120
Пусть объем будет прописан непосредственно из условия) 100

2024-09-25 19:00 UTC, ievetrovdev commented on src/main/kotlin/lesson4/lesson4_task2.kt
> +            " ${(packageWeight1 in (MINIMUM_WEIGHT + 1)..MAX_WEIGHT && packageVolume1 < MAX_VOLUME)}")
"Голые" числа - [магические ](https://ru.wikipedia.org/wiki/Магическое_число_(программирование)#Плохая_практика_программирования) числа, что тоже не является хорошей практикой.

2024-09-26 05:25 UTC, BerStep commented on src/main/kotlin/lesson4/lesson4_task2.kt
> +const val MAX_VOLUME = 120
Поторопился, взял 120 из приложенного примера..

2024-09-26 05:26 UTC, BerStep commented on src/main/kotlin/lesson4/lesson4_task2.kt
> +            " ${(packageWeight1 in (MINIMUM_WEIGHT + 1)..MAX_WEIGHT && packageVolume1 < MAX_VOLUME)}")
![KS-4-2](https://github.com/user-attachments/assets/30ac8d05-9c9f-4422-8f6c-7685e154691d)
Вопрос, если преобразовать как предлагает программа, Получается так лучше не делать в данном случае?

2024-09-26 19:14 UTC, ievetrovdev commented on src/main/kotlin/lesson4/lesson4_task2.kt
> +            " ${(packageWeight1 in (MINIMUM_WEIGHT + 1)..MAX_WEIGHT && packageVolume1 < MAX_VOLUME)}")
В целом можно проверять и в диапазоне, здесь больше вопрос к "голому" числу и что оно означает, со стороны не сразу очевидно, для чего оно здесь

2024-09-26 19:14 UTC, ievetrovdev approved these changes
Аппрув!

2024-09-26 19:48 UTC, merged