KS-4-4-operators create
BerStep/KotlinSprint pull request #23
Opened 2024-09-25 11:44 UTC by BerStep

2024-09-25 19:04 UTC, ievetrovdev requested changes

2024-09-25 19:04 UTC, ievetrovdev commented on src/main/kotlin/lesson4/lessoon4_task4.kt
> +    val handsAndPress = kindTraining == 1
Лучше вынести нахождение четности (только четности) числа в отдельный флаг и применять его уже при выводе напрямую или с отрицанием (инвертируя).

2024-09-25 19:04 UTC, ievetrovdev commented on src/main/kotlin/lesson4/lessoon4_task4.kt
> +    val footAndBack = kindTraining == 0
Boolean переменные принято называть isSomeSituation (не обязательно, но так код легче читается).

2024-09-26 19:16 UTC, ievetrovdev requested changes

2024-09-26 19:16 UTC, ievetrovdev commented on src/main/kotlin/lesson4/lessoon4_task4.kt
> +    val isSomeSituation = trainingDay % 2 == 0
isSomeSituation - лишь пример, дословно "это какая-то ситуация")
Здесь больше подойдет название isEvenDay

2024-09-26 20:11 UTC, BerStep commented on src/main/kotlin/lesson4/lessoon4_task4.kt
> +    val isSomeSituation = trainingDay % 2 == 0
С неймингом надо будет еще поработать))

2024-09-27 14:45 UTC, ievetrovdev approved these changes
Прекрасное решение!

2024-09-27 14:46 UTC, merged