KS-4-5-operators create
BerStep/KotlinSprint pull request #24
Opened 2024-09-25 12:19 UTC by BerStep

Хорошо что IDEA может предлагать и исправлять косяки в коде =)

2024-09-25 19:05 UTC, ievetrovdev requested changes

2024-09-25 19:05 UTC, ievetrovdev commented on src/main/kotlin/lesson4/lession4_task5.kt
> +                (provisionsShip!! > PROVISIONS_SHIP) && (favorableWeather == FAVORABLE_WEATHER)) ||
Использование оператора !! подразумевает, что ты уверен в том, что значение не может быть null. Однако, если это не так, то приложение "упадет" с ошибкой.
Это противоречит основной идее безопасности типов в Kotlin, поэтому лучше использовать альтернативные способы обработки нулабельных значений. такие как оператор безопасного вызова ?., элвис-оператор ?: или оператор let

2024-09-25 19:05 UTC, ievetrovdev commented on src/main/kotlin/lesson4/lession4_task5.kt
> +    val damageOfShip = readlnOrNull().toBoolean()
Неочевидный нейминг переменных. также напоминаю, что boolean переменные именуются в основном начиная с is

2024-09-26 19:21 UTC, ievetrovdev requested changes

2024-09-26 19:21 UTC, ievetrovdev commented on src/main/kotlin/lesson4/lession4_task5.kt
> +    println("Вы ввели: $isDamageOfShip")
Хорошо, аппрув! но рекомендую на будущее отделять блок с определением переменных от всего остального кода пустой строкой. Чтобы код выглядел менее монолитным, а соответственно лучше читаемым.

2024-09-26 19:21 UTC, ievetrovdev commented on src/main/kotlin/lesson4/lession4_task5.kt
> +    val shipReadiness: Boolean =
Эта переменная также хранит boolean значение)

2024-09-26 20:22 UTC, BerStep commented
Сделал пустые строки, оформил правильно?

2024-09-27 14:46 UTC, ievetrovdev approved these changes
Да, теперь все верно!

2024-09-27 14:49 UTC, merged