KS-1-5-variables create
BerStep/KotlinSprint pull request #9
Opened 2024-09-19 19:53 UTC by BerStep

2024-09-20 21:31 UTC, ievetrovdev requested changes
Я оставил комментарии для доработки. чтобы правильно залить изменения, надо:
 - переключиться в Идее на нужную ветку
 - внести изменения и сделать коммит в эту ветку (следить чтобы в стейдж не добавились лишние задачи, которые не относятся к данной задаче)
 - отправить ссылку в бот на этот же пулл реквест к соответствующей задаче

2024-09-20 21:31 UTC, ievetrovdev commented on src/main/kotlin/lesson1/lesson1_task5.kt
> +    println("0$hour:${minute % 60}:0${second % 60}")
Так как это 5 задача ("со звездочкой") не по уровню урока, то предлагаю использовать более элегантное решение). (может потребовать дополнительного ресерча). Для корректного вывода нуля вначале попробуй посмотреть в сторону String.format().

2024-09-20 21:31 UTC, ievetrovdev commented on src/main/kotlin/lesson1/lesson1_task5.kt
> +    val hour: Int = minute / 60
Чтобы снизить риск ошибок, предлагаю еще вынести 60 в константу. Кроме того это магическое число, что тоже не является хорошей практикой.

2024-09-20 21:31 UTC, ievetrovdev commented on src/main/kotlin/lesson1/lesson1_task5.kt
> +    println("0$hour:${minute % 60}:0${second % 60}")
Все расчеты лучше выполнять до вывода на экран

2024-09-21 08:26 UTC, BerStep commented
Но тут возникает вопрос, данный формат подходит, если мы знаем значение результата. А именно, если бы время было не 1 час, а 15,  то код надо переписывать.  Как понимаю этому научимся, когда будем разбирать условия if.

2024-09-21 18:23 UTC, ievetrovdev requested changes

2024-09-21 18:23 UTC, ievetrovdev commented on src/main/kotlin/lesson1/lesson1_task5.kt
> +    hour %= 24
Чтобы снизить риск ошибок, предлагаю еще вынести 24 в константу. Кроме того это магическое число, что тоже не является хорошей практикой.

2024-09-21 18:23 UTC, ievetrovdev commented on src/main/kotlin/lesson1/lesson1_task5.kt
> +    val time = String.format("0%d:%d:0%d", hour, minute, second)
Так как это 5 задача ("со звездочкой") не по уровню урока, то предлагаю использовать более элегантное решение). (может потребовать дополнительного ресерча). Для корректного вывода нуля вначале попробуй посмотреть в сторону String.format().

2024-09-21 18:25 UTC, ievetrovdev requested changes
Я оставил комментарии для доработки. чтобы правильно залить изменения, надо:
 - переключиться в Идее на нужную ветку
 - внести изменения и сделать коммит в эту ветку (следить чтобы в стейдж не добавились лишние задачи, которые не относятся к данной задаче)
 - отправить ссылку в бот на этот же пулл реквест к соответствующей задаче

2024-09-22 20:10 UTC, BerStep commented
Вопрос, как лучше подписывать коммиты, когда их много в одной ветке?

2024-09-22 20:21 UTC, ievetrovdev approved these changes
Все верно, отлично! Теперь эту ветку можно мержить в мастер. напомню, перед созданием новой ветки надо переключиться в мастер, обновить его (чтобы слитые изменения прилетели в локальный проект) и только тогда бранчиться

2024-09-23 07:40 UTC, merged